### ISSUE TITLE
'Trainer' object has no attribute 'strategy'

### ISSUE THREAD

**Issue by HoiMinJeong** [victorchall/EveryDream-trainer#4]
Error Occur.....

Training: 0it [00:00, ?it/s]Training halted. Summoning checkpoint as last.ckpt
Training complete. max_steps or max_epochs reached, or we blew up.

Traceback (most recent call last):
  File "main.py", line 754, in <module>
    trainer.fit(model, data)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\loops\base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 137, in on_run_start
    self.trainer.call_hook("on_train_epoch_start")
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1495, in call_hook
    callback_fx(*args, **kwargs)
  File "C:\Users\tkgix\.conda\envs\everydream\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 88, in on_train_epoch_start
    callback.on_train_epoch_start(self, self.lightning_module)
  File "E:\AI_Tools\_EveryDream-trainer\EveryDream-trainer\main.py", line 461, in on_train_epoch_start
    torch.cuda.reset_peak_memory_stats(trainer.strategy.root_device.index)
AttributeError: 'Trainer' object has no attribute 'strategy'

**Comment by nawnie** [comment]
what was the cause of this cause im getting this error often
